Dynamic legend
Aquaveo/tethysext-atcore pull request #16
Opened 2020-11-13 18:41 UTC by msouff

2020-11-16 18:06 UTC, swainn requested changes
Remove the __init__.py from tethysext.

2020-11-16 21:34 UTC, htran84 commented on tethysext/atcore/controllers/map_view.py
> +        legend = {
build_legend method is used to build the legend based on a given layer in the result. This method build the legend based on the parameters used in the generate_custom_color_ramp_divisions method. These parameters are coming from the ajax call. I don't see how we want to use the build_legend method here.

2020-11-17 16:50 UTC, htran84 commented on tethysext/atcore/controllers/resource_workflows/results_views/map_workflow_results_view.py
> +            'show_legends': self.show_legends,
True. Removed it.

2020-11-17 16:50 UTC, htran84 commented on tethysext/atcore/controllers/resource_workflows/results_views/map_workflow_results_view.py
> +        legends_select_input = []
updated

2020-11-17 16:53 UTC, htran84 commented on tethysext/atcore/controllers/resource_workflows/results_views/report_workflow_results_view.py
> +                        # map_view.layers.insert(0, result_layer)
Updated

2020-11-17 16:54 UTC, htran84 commented on tethysext/atcore/models/resource_workflow_results/spatial_workflow_result.py
> +            maximum(float): Maximum value of the wms layer
updated

2020-11-17 16:55 UTC, htran84 commented on tethysext/atcore/models/resource_workflow_results/spatial_workflow_result.py
> +        """  # noqa: E501\
updated

2020-11-17 17:50 UTC, msouff commented on tethysext/atcore/public/map_view/atcore_cesium_map_view.js
> +window.ATCORE_MAP_VIEW = ATCORE_MAP_VIEW;
And import always inserts stuff to the current scope. ATCORE_MAP_VIEW needs to be global.

2020-11-17 23:42 UTC, swainn requested changes

2020-11-17 23:42 UTC, swainn commented on tethysext/atcore/controllers/map_view.py
> +            'atcore/resource_workflows/components/map_view_color_ramp_component.html',
Move this template to `templates/map_view/color_ramp_component.html`

2020-11-17 23:44 UTC, msouff commented on tethysext/atcore/cli/cli_helpers.py
> -def print_warning(statement):
Because we don't use it anywhere.

2020-11-17 23:44 UTC, swainn commented on tethysext/atcore/services/map_manager.py
> +            options['minimum'] = color_ramp_division_kwargs['min_value']
BTW, on the JavaScript side of things, you get the data attributes from layer.tethys_data.

2020-11-18 21:28 UTC, merged